<?php
/**
 * Framework Generator Exporter
 *
 * Handles exporting framework briefs to DOCX and HTML formats.
 */

if (!defined('ABSPATH')) {
    exit;
}

class Framework_Generator_Exporter {

    /**
     * Export directory
     */
    const EXPORT_DIR = 'fg_exports';

    /**
     * Export framework brief to DOCX
     */
    public function export_to_docx($brief_id) {
        $db = new Dual_GPT_DB_Handler();
        $brief = $db->get_framework_brief($brief_id);

        if (!$brief) {
            return new WP_Error('brief_not_found', 'Framework brief not found');
        }

        // Load PHPWord if available
        if (!class_exists('PhpOffice\\PhpWord\\PhpWord')) {
            return new WP_Error('phpword_not_found', 'PHPWord library not available');
        }

        $phpWord = new \PhpOffice\PhpWord\PhpWord();

        // Add title page
        $section = $phpWord->addSection();
        $section->addTitle($brief['title'], 1);
        $section->addText('Generated by Framework Generator');
        $section->addText('Created: ' . date('F j, Y', strtotime($brief['created_at'])));

        // Add framework content
        $section->addPageBreak();
        $section->addTitle('Framework Overview', 1);
        $section->addText($brief['overview']);

        // Add sections
        if (!empty($brief['sections'])) {
            $sections = json_decode($brief['sections'], true);
            foreach ($sections as $section_data) {
                $section->addPageBreak();
                $section->addTitle($section_data['title'], 2);
                $section->addText($section_data['content']);
            }
        }

        // Add provenance appendix
        $this->add_provenance_appendix_docx($section, $brief_id);

        // Save file
        $filename = 'framework-' . $brief_id . '-' . date('Y-m-d-H-i-s') . '.docx';
        $filepath = $this->get_export_path($filename);

        $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
        $objWriter->save($filepath);

        // Store in database
        $file_url = $this->get_export_url($filename);
        $this->store_export_record($brief_id, 'docx', $file_url, $filepath);

        return array(
            'file_url' => $file_url,
            'file_path' => $filepath,
            'filename' => $filename,
        );
    }

    /**
     * Export framework brief to HTML
     */
    public function export_to_html($brief_id) {
        $db = new Dual_GPT_DB_Handler();
        $brief = $db->get_framework_brief($brief_id);

        if (!$brief) {
            return new WP_Error('brief_not_found', 'Framework brief not found');
        }

        $html = $this->generate_html_content($brief);

        // Save file
        $filename = 'framework-' . $brief_id . '-' . date('Y-m-d-H-i-s') . '.html';
        $filepath = $this->get_export_path($filename);

        file_put_contents($filepath, $html);

        // Store in database
        $file_url = $this->get_export_url($filename);
        $this->store_export_record($brief_id, 'html', $file_url, $filepath);

        return array(
            'file_url' => $file_url,
            'file_path' => $filepath,
            'filename' => $filename,
        );
    }

    /**
     * Generate HTML content
     */
    private function generate_html_content($brief) {
        $html = '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>' . esc_html($brief['title']) . '</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; margin: 40px; }
        h1 { color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; }
        h2 { color: #666; margin-top: 30px; }
        .meta { color: #888; font-size: 0.9em; margin-bottom: 20px; }
        .section { margin-bottom: 30px; }
        .provenance { background: #f9f9f9; padding: 20px; margin-top: 40px; border-left: 4px solid #333; }
        .citation { margin: 10px 0; padding: 10px; background: white; border: 1px solid #ddd; }
        .observation { font-style: italic; color: #666; }
    </style>
</head>
<body>
    <h1>' . esc_html($brief['title']) . '</h1>
    <div class="meta">
        Generated by Framework Generator<br>
        Created: ' . date('F j, Y', strtotime($brief['created_at'])) . '
    </div>

    <h2>Framework Overview</h2>
    <div class="section">
        ' . nl2br(esc_html($brief['overview'])) . '
    </div>';

        // Add sections
        if (!empty($brief['sections'])) {
            $sections = json_decode($brief['sections'], true);
            foreach ($sections as $section_data) {
                $html .= '
    <h2>' . esc_html($section_data['title']) . '</h2>
    <div class="section">
        ' . nl2br(esc_html($section_data['content'])) . '
    </div>';
            }
        }

        // Add provenance appendix
        $html .= $this->generate_provenance_appendix_html($brief['id']);

        $html .= '
</body>
</html>';

        return $html;
    }

    /**
     * Add provenance appendix to DOCX
     */
    private function add_provenance_appendix_docx($section, $brief_id) {
        $section->addPageBreak();
        $section->addTitle('Provenance Appendix', 1);
        $section->addText('This appendix contains the source citations and observations used to generate this framework.');

        $citations = $this->get_citations_for_brief($brief_id);

        foreach ($citations as $citation) {
            $section->addTextBreak(1);
            $section->addTitle('Citation: ' . $citation['title'], 3);

            if (!empty($citation['apa_string']) && $citation['apa_string'] !== 'details_unavailable') {
                $section->addText('APA Citation: ' . $citation['apa_string']);
            }

            $section->addText('Source: ' . $citation['url']);
            $section->addText('Authority Score: ' . $citation['authority_score']);

            // Add observations
            $observations = $this->get_observations_for_citation($citation['id']);
            if (!empty($observations)) {
                $section->addText('Key Observations:', array('bold' => true));
                foreach ($observations as $observation) {
                    $section->addText('• ' . $observation['observation']);
                    $section->addText('  Supporting Passage: ' . $observation['passage_snippet'], array('italic' => true));
                }
            }
        }
    }

    /**
     * Generate provenance appendix for HTML
     */
    private function generate_provenance_appendix_html($brief_id) {
        $html = '

    <div class="provenance">
        <h2>Provenance Appendix</h2>
        <p>This appendix contains the source citations and observations used to generate this framework.</p>';

        $citations = $this->get_citations_for_brief($brief_id);

        foreach ($citations as $citation) {
            $html .= '
        <div class="citation">
            <h3>' . esc_html($citation['title']) . '</h3>';

            if (!empty($citation['apa_string']) && $citation['apa_string'] !== 'details_unavailable') {
                $html .= '<p><strong>APA Citation:</strong> ' . esc_html($citation['apa_string']) . '</p>';
            }

            $html .= '<p><strong>Source:</strong> <a href="' . esc_url($citation['url']) . '">' . esc_html($citation['url']) . '</a></p>';
            $html .= '<p><strong>Authority Score:</strong> ' . esc_html($citation['authority_score']) . '</p>';

            // Add observations
            $observations = $this->get_observations_for_citation($citation['id']);
            if (!empty($observations)) {
                $html .= '<h4>Key Observations:</h4>';
                foreach ($observations as $observation) {
                    $html .= '<div class="observation">';
                    $html .= '<p>' . esc_html($observation['observation']) . '</p>';
                    $html .= '<p><em>Supporting Passage: ' . esc_html($observation['passage_snippet']) . '</em></p>';
                    $html .= '</div>';
                }
            }

            $html .= '
        </div>';
        }

        $html .= '
    </div>';

        return $html;
    }

    /**
     * Get citations for brief
     */
    private function get_citations_for_brief($brief_id) {
        global $wpdb;
        return $wpdb->get_results(
            $wpdb->prepare(
                "SELECT * FROM {$wpdb->prefix}fg_validated_citations WHERE brief_id = %d ORDER BY authority_score DESC",
                $brief_id
            ),
            ARRAY_A
        );
    }

    /**
     * Get observations for citation
     */
    private function get_observations_for_citation($citation_id) {
        // This would need to be implemented based on how observations are stored
        // For now, return empty array
        return array();
    }

    /**
     * Get export path
     */
    private function get_export_path($filename) {
        $upload_dir = wp_upload_dir();
        $export_dir = $upload_dir['basedir'] . '/' . self::EXPORT_DIR;

        if (!file_exists($export_dir)) {
            wp_mkdir_p($export_dir);
        }

        return $export_dir . '/' . $filename;
    }

    /**
     * Get export URL
     */
    private function get_export_url($filename) {
        $upload_dir = wp_upload_dir();
        return $upload_dir['baseurl'] . '/' . self::EXPORT_DIR . '/' . $filename;
    }

    /**
     * Store export record
     */
    private function store_export_record($brief_id, $format, $file_url, $file_path) {
        global $wpdb;

        $result = $wpdb->insert(
            $wpdb->prefix . 'fg_exports',
            array(
                'brief_id' => $brief_id,
                'format'    => $format,
                'file_url'  => $file_url,
                'file_path' => $file_path,
                'created_at'=> current_time('mysql'),
            ),
            array('%d', '%s', '%s', '%s', '%s')
        );

        if ($result === false) {
            error_log(
                sprintf(
                    'Failed to insert framework export record for brief_id %d (format: %s): %s',
                    (int) $brief_id,
                    $format,
                    isset($wpdb->last_error) ? $wpdb->last_error : 'Unknown database error'
                )
            );
        }
    }
}