<?php
/**
 * TouchPoint Database Backup and Rollback System
 * Provides automated backup and restore functionality
 */

if (!defined('ABSPATH')) {
    exit;
}

class TouchPoint_Backup_Manager {
    
    private $wpdb;
    private $backup_dir;
    private $max_backups = 10;
    
    public function __construct() {
        global $wpdb;
        $this->wpdb = $wpdb;
        $this->backup_dir = WP_CONTENT_DIR . '/touchpoint-backups';
        
        // Ensure backup directory exists
        if (!file_exists($this->backup_dir)) {
            wp_mkdir_p($this->backup_dir);
            
            // Add .htaccess to protect backup files
            $htaccess_content = "Order Deny,Allow\nDeny from all\n";
            file_put_contents($this->backup_dir . '/.htaccess', $htaccess_content);
            
            // Add index.php to prevent directory listing
            file_put_contents($this->backup_dir . '/index.php', '<?php // Silence is golden');
        }
    }
    
    /**
     * Create a complete backup of all TouchPoint tables
     */
    public function create_backup($description = '') {
        $backup_id = date('Y_m_d_H_i_s') . '_' . uniqid();
        $backup_file = $this->backup_dir . '/backup_' . $backup_id . '.sql';
        
        try {
            $backup_content = $this->generate_backup_content($backup_id, $description);
            
            $bytes_written = file_put_contents($backup_file, $backup_content);
            
            if ($bytes_written === false) {
                throw new Exception("Could not write backup file");
            }
            
            // Record backup in database
            $this->record_backup($backup_id, $backup_file, $description, $bytes_written);
            
            // Clean up old backups
            $this->cleanup_old_backups();
            
            return [
                'success' => true,
                'backup_id' => $backup_id,
                'file' => $backup_file,
                'size' => $bytes_written,
                'message' => 'Backup created successfully'
            ];
            
        } catch (Exception $e) {
            return [
                'success' => false,
                'error' => $e->getMessage(),
                'message' => 'Backup failed: ' . $e->getMessage()
            ];
        }
    }
    
    /**
     * Generate backup SQL content
     */
    private function generate_backup_content($backup_id, $description) {
        $content = "-- TouchPoint Marketing Suite Database Backup\n";
        $content .= "-- Backup ID: {$backup_id}\n";
        $content .= "-- Created: " . date('Y-m-d H:i:s') . "\n";
        $content .= "-- WordPress Site: " . get_site_url() . "\n";
        $content .= "-- Description: " . esc_sql($description) . "\n";
        $content .= "-- Generated by TouchPoint Backup Manager\n\n";
        
        $content .= "SET FOREIGN_KEY_CHECKS = 0;\n";
        $content .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
        $content .= "SET time_zone = \"+00:00\";\n\n";
        
        $touchpoint_tables = $this->get_touchpoint_tables();
        
        foreach ($touchpoint_tables as $table) {
            $full_table_name = $this->wpdb->prefix . $table;
            
            // Check if table exists
            if ($this->wpdb->get_var("SHOW TABLES LIKE '{$full_table_name}'") != $full_table_name) {
                continue;
            }
            
            $content .= $this->backup_table($full_table_name, $table);
        }
        
        $content .= "\nSET FOREIGN_KEY_CHECKS = 1;\n";
        $content .= "-- Backup completed successfully\n";
        
        return $content;
    }
    
    /**
     * Backup individual table structure and data
     */
    private function backup_table($full_table_name, $table_name) {
        $content = "\n-- --------------------------------------------------------\n";
        $content .= "-- Table structure for table `{$table_name}`\n";
        $content .= "-- --------------------------------------------------------\n\n";
        
        // Get table structure
        $create_table = $this->wpdb->get_row("SHOW CREATE TABLE `{$full_table_name}`", ARRAY_A);
        
        if ($create_table) {
            $content .= "DROP TABLE IF EXISTS `{$full_table_name}`;\n";
            $content .= $create_table['Create Table'] . ";\n\n";
            
            // Get table data
            $content .= "-- Dumping data for table `{$table_name}`\n\n";
            
            $rows = $this->wpdb->get_results("SELECT * FROM `{$full_table_name}`", ARRAY_A);
            
            if (!empty($rows)) {
                $content .= "LOCK TABLES `{$full_table_name}` WRITE;\n";
                $content .= "/*!40000 ALTER TABLE `{$full_table_name}` DISABLE KEYS */;\n";
                
                foreach ($rows as $row) {
                    $values = [];
                    foreach ($row as $value) {
                        if (is_null($value)) {
                            $values[] = 'NULL';
                        } else {
                            $values[] = "'" . esc_sql($value) . "'";
                        }
                    }
                    $content .= "INSERT INTO `{$full_table_name}` VALUES (" . implode(', ', $values) . ");\n";
                }
                
                $content .= "/*!40000 ALTER TABLE `{$full_table_name}` ENABLE KEYS */;\n";
                $content .= "UNLOCK TABLES;\n\n";
            } else {
                $content .= "-- No data for table `{$table_name}`\n\n";
            }
        }
        
        return $content;
    }
    
    /**
     * Get list of all TouchPoint tables
     */
    private function get_touchpoint_tables() {
        return [
            'khm_membership_levels',
            'khm_membership_levelmeta',
            'khm_memberships_users',
            'khm_membership_orders',
            'khm_user_credits',
            'khm_credit_usage',
            'khm_article_products',
            'khm_shopping_cart',
            'khm_purchases',
            'khm_member_library',
            'khm_library_categories',
            'khm_gifts',
            'khm_gift_redemptions',
            'khm_email_queue',
            'khm_email_logs',
            'khm_discount_codes',
            'khm_discount_codes_levels',
            'khm_discount_codes_uses',
            'khm_migrations'
        ];
    }
    
    /**
     * Record backup metadata in database
     */
    private function record_backup($backup_id, $file_path, $description, $file_size) {
        $table_name = $this->wpdb->prefix . 'touchpoint_backups';
        
        // Create backups table if it doesn't exist
        $charset_collate = $this->wpdb->get_charset_collate();
        $sql = "CREATE TABLE IF NOT EXISTS {$table_name} (
            id int(11) NOT NULL AUTO_INCREMENT,
            backup_id varchar(255) NOT NULL,
            file_path varchar(500) NOT NULL,
            description text,
            file_size bigint,
            tables_count int,
            created_at datetime DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id),
            UNIQUE KEY backup_id (backup_id)
        ) {$charset_collate};";
        
        require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
        dbDelta($sql);
        
        // Insert backup record
        $this->wpdb->insert(
            $table_name,
            [
                'backup_id' => $backup_id,
                'file_path' => $file_path,
                'description' => $description,
                'file_size' => $file_size,
                'tables_count' => count($this->get_touchpoint_tables())
            ],
            ['%s', '%s', '%s', '%d', '%d']
        );
    }
    
    /**
     * Get list of all available backups
     */
    public function get_backup_list() {
        $table_name = $this->wpdb->prefix . 'touchpoint_backups';
        
        // Check if backups table exists
        if ($this->wpdb->get_var("SHOW TABLES LIKE '{$table_name}'") != $table_name) {
            return [];
        }
        
        $backups = $this->wpdb->get_results(
            "SELECT * FROM {$table_name} ORDER BY created_at DESC",
            ARRAY_A
        );
        
        // Add file existence check and human readable sizes
        foreach ($backups as &$backup) {
            $backup['file_exists'] = file_exists($backup['file_path']);
            $backup['file_size_human'] = $this->format_file_size($backup['file_size']);
            $backup['created_ago'] = human_time_diff(strtotime($backup['created_at'])) . ' ago';
        }
        
        return $backups;
    }
    
    /**
     * Restore database from backup
     */
    public function restore_backup($backup_id) {
        try {
            $backup = $this->get_backup_by_id($backup_id);
            
            if (!$backup) {
                throw new Exception("Backup not found: {$backup_id}");
            }
            
            if (!file_exists($backup['file_path'])) {
                throw new Exception("Backup file missing: {$backup['file_path']}");
            }
            
            // Create a safety backup before restore
            $safety_backup = $this->create_backup("Pre-restore safety backup");
            
            if (!$safety_backup['success']) {
                throw new Exception("Could not create safety backup: " . $safety_backup['error']);
            }
            
            // Read and execute backup SQL
            $sql_content = file_get_contents($backup['file_path']);
            
            if ($sql_content === false) {
                throw new Exception("Could not read backup file");
            }
            
            $this->execute_sql_backup($sql_content);
            
            return [
                'success' => true,
                'message' => 'Database restored successfully',
                'safety_backup' => $safety_backup['backup_id']
            ];
            
        } catch (Exception $e) {
            return [
                'success' => false,
                'error' => $e->getMessage(),
                'message' => 'Restore failed: ' . $e->getMessage()
            ];
        }
    }
    
    /**
     * Execute SQL backup content
     */
    private function execute_sql_backup($sql_content) {
        // Remove comments and split statements
        $sql_content = preg_replace('/--.*$/m', '', $sql_content);
        $sql_content = preg_replace('/\/\*.*?\*\//s', '', $sql_content);
        
        $statements = explode(';', $sql_content);
        
        foreach ($statements as $statement) {
            $statement = trim($statement);
            
            if (empty($statement)) {
                continue;
            }
            
            $result = $this->wpdb->query($statement);
            
            if ($result === false) {
                throw new Exception("SQL Error: " . $this->wpdb->last_error);
            }
        }
    }
    
    /**
     * Get backup by ID
     */
    private function get_backup_by_id($backup_id) {
        $table_name = $this->wpdb->prefix . 'touchpoint_backups';
        
        return $this->wpdb->get_row(
            $this->wpdb->prepare(
                "SELECT * FROM {$table_name} WHERE backup_id = %s",
                $backup_id
            ),
            ARRAY_A
        );
    }
    
    /**
     * Delete backup
     */
    public function delete_backup($backup_id) {
        try {
            $backup = $this->get_backup_by_id($backup_id);
            
            if (!$backup) {
                throw new Exception("Backup not found");
            }
            
            // Delete file
            if (file_exists($backup['file_path'])) {
                if (!unlink($backup['file_path'])) {
                    throw new Exception("Could not delete backup file");
                }
            }
            
            // Remove from database
            $table_name = $this->wpdb->prefix . 'touchpoint_backups';
            $this->wpdb->delete(
                $table_name,
                ['backup_id' => $backup_id],
                ['%s']
            );
            
            return [
                'success' => true,
                'message' => 'Backup deleted successfully'
            ];
            
        } catch (Exception $e) {
            return [
                'success' => false,
                'error' => $e->getMessage(),
                'message' => 'Delete failed: ' . $e->getMessage()
            ];
        }
    }
    
    /**
     * Clean up old backups (keep only max_backups)
     */
    private function cleanup_old_backups() {
        $table_name = $this->wpdb->prefix . 'touchpoint_backups';
        
        $old_backups = $this->wpdb->get_results(
            $this->wpdb->prepare(
                "SELECT backup_id, file_path FROM {$table_name} 
                 ORDER BY created_at DESC 
                 LIMIT %d, 1000",
                $this->max_backups
            ),
            ARRAY_A
        );
        
        foreach ($old_backups as $backup) {
            $this->delete_backup($backup['backup_id']);
        }
    }
    
    /**
     * Format file size in human readable format
     */
    private function format_file_size($size) {
        $units = ['B', 'KB', 'MB', 'GB'];
        $unit_index = 0;
        
        while ($size >= 1024 && $unit_index < count($units) - 1) {
            $size /= 1024;
            $unit_index++;
        }
        
        return round($size, 2) . ' ' . $units[$unit_index];
    }
    
    /**
     * Get backup directory size
     */
    public function get_backup_directory_size() {
        $total_size = 0;
        $files = glob($this->backup_dir . '/backup_*.sql');
        
        foreach ($files as $file) {
            $total_size += filesize($file);
        }
        
        return [
            'bytes' => $total_size,
            'human' => $this->format_file_size($total_size),
            'files' => count($files)
        ];
    }
}

// Create backup manager instance for use in WordPress
if (!function_exists('touchpoint_get_backup_manager')) {
    function touchpoint_get_backup_manager() {
        static $backup_manager = null;
        
        if ($backup_manager === null) {
            $backup_manager = new TouchPoint_Backup_Manager();
        }
        
        return $backup_manager;
    }
}